# Generated by Django 4.1.5 on 2023-01-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password_hash', models.TextField()),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
