# Generated by Django 4.1.4 on 2023-01-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultyVoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=999)),
                ('answer1', models.CharField(max_length=999)),
                ('answer2', models.CharField(max_length=999)),
                ('answer3', models.CharField(max_length=999)),
                ('answer4', models.CharField(max_length=999)),
                ('answer5', models.CharField(max_length=999)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
