# Generated by Django 4.1.4 on 2023-02-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0003_answers_questions_voices_delete_multyvoicehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Voices',
        ),
    ]
