# Generated by Django 4.1.4 on 2023-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_web', '0004_delete_answers_delete_questions_delete_voices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.IntegerField(default=0)),
                ('answer_number', models.IntegerField(default=0)),
                ('author', models.CharField(default='Anonim', max_length=999)),
                ('answer', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.IntegerField(default=0)),
                ('voice_type', models.CharField(default='', max_length=10)),
                ('answer_number', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=999)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Voices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type', models.CharField(default='', max_length=10)),
                ('author', models.CharField(default='Anonim', max_length=999)),
                ('question', models.CharField(max_length=999)),
            ],
        ),
    ]
