# Generated by Django 4.1.4 on 2023-02-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Voices',
        ),
    ]
