# Generated by Django 4.1.4 on 2023-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voices',
            name='voice_picture',
            field=models.CharField(max_length=999),
        ),
    ]
