# Generated by Django 4.1.4 on 2023-02-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0008_alter_voices_voice_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Voices',
        ),
    ]
